=== yxx010/moocstudy/src/main/java/com/imooc/stage2/step3/1/XML入门/plan.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT plan (item*)>
<!ELEMENT item (sourse-name,class-hour,exam-form)>
<!ATTLIST item no CDATA "">
<!ELEMENT sourse-name (#PCDATA)>
<!ELEMENT class-hour (#PCDATA)>
<!ELEMENT exam-form (#PCDATA)>

=== yxx010/moocstudy/src/main/java/com/imooc/stage2/step3/1/XML入门/plan.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plan SYSTEM "plan.dtd">
<plan>
    <item no="1">
        <sourse-name>大学英语</sourse-name>
        <class-hour>36</class-hour>
        <exam-form>考试</exam-form>
    </item>
    <item no="2">
        <sourse-name>高等数学</sourse-name>
        <class-hour>70</class-hour>
        <exam-form>考试</exam-form>
    </item>
    <item no="3">
        <sourse-name>计算机应用基础</sourse-name>
        <class-hour>108</class-hour>
        <exam-form>上机考试</exam-form>
    </item>
</plan>
